apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql
    tier: database
spec:
  selector:
    matchLabels:
      app: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql
        tier: database
    spec:
      containers:
        - name: postgresql
          image: postgres:14
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_DB
              value: northwind
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: changeme
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql-claim0
              mountPath: /var/lib/postgresql/data
              subPath: mydata

            - mountPath: /docker-entrypoint-initdb.d
              name: postgresql-initdb
      volumes:
        - name: postgresql-claim0
          persistentVolumeClaim:
            claimName: postgresql-claim1

        - name: postgresql-initdb
          configMap:
            name: postgresql-initdb-config

---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: postgres
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: postgres
#  template:
#    metadata:
#      labels:
#        app: postgres
#    spec:
#      containers:
#        - name: postgres
#          image: 'postgres:14'
#          imagePullPolicy: IfNotPresent
#          ports:
#            - containerPort: 5432
#          envFrom:
#            - configMapRef:
#                name: postgres-secret
#          volumeMounts:
#            - mountPath: /var/lib/postgresql/data
#              name: postgresdata
#            - mountPath: /docker-entrypoint-initdb.d
#              name: postgresql-initdb
#      volumes:
#        - name: postgresdata
#          persistentVolumeClaim:
#            claimName: postgresql-claim0
#        - name: postgresql-initdb
#          configMap:
#           name: postgresql-initdb-config




